export const TABLE_RESIZE = 'TABLE_RESIZE'
export const TEXT_CHANGE = 'TEXT_CHANGE'
export const STYLES_CHANGE = 'STYLES_CHANGE'
export const APPLY_STYLES = 'APPLY_STYLES'
export const TITLE_CHANGE = 'TITLE_CHANGE'

